#!/bin/bash
# Frontend CDK deployment script - Deploy CloudFront and S3 infrastructure
# This script deploys the FrontendStack using AWS CDK

set -euo pipefail

# Get the repository root directory
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CDK_DIR="${REPO_ROOT}/infrastructure"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

# Load environment variables
log_info "Loading environment configuration..."
if [ -f "${REPO_ROOT}/scripts/common/load-env.sh" ]; then
    # shellcheck source=../common/load-env.sh
    source "${REPO_ROOT}/scripts/common/load-env.sh"
else
    log_error "Environment loader not found: ${REPO_ROOT}/scripts/common/load-env.sh"
    exit 1
fi

# Check if CDK directory exists
if [ ! -d "${CDK_DIR}" ]; then
    log_error "CDK directory not found: ${CDK_DIR}"
    exit 1
fi

# Check if CDK is installed
if ! command -v cdk &> /dev/null; then
    log_error "AWS CDK is not installed. Please install it first."
    log_error "Run: scripts/common/install-deps.sh"
    exit 1
fi

log_info "Deploying Frontend Stack..."
log_info "CDK directory: ${CDK_DIR}"
log_info "Project prefix: ${CDK_PROJECT_PREFIX}"
log_info "AWS Region: ${CDK_AWS_REGION}"
log_info "AWS Account: ${CDK_AWS_ACCOUNT}"

# Change to CDK directory
cd "${CDK_DIR}"

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    log_warn "node_modules not found in CDK directory. Installing dependencies..."
    npm install
fi

# Display CDK version
log_info "CDK version: $(cdk --version)"

# Bootstrap CDK if needed (idempotent operation)
# Note: Run from project root to avoid loading CDK app context (see CLAUDES_LESSONS_PHASE4.md Challenge 1)
log_info "Ensuring CDK is bootstrapped in ${CDK_AWS_REGION}..."
cd "${REPO_ROOT}"
cdk bootstrap aws://${CDK_AWS_ACCOUNT}/${CDK_AWS_REGION} \
    || log_info "CDK already bootstrapped or bootstrap failed (continuing anyway)"
cd infrastructure/

# Check if pre-synthesized template exists
if [ -d "cdk.out" ] && [ -f "cdk.out/FrontendStack.template.json" ]; then
    log_info "Using pre-synthesized CloudFormation template from cdk.out/"
    CDK_APP="cdk.out/"
else
    log_info "No pre-synthesized template found. CDK will synthesize during deployment."
    CDK_APP=""
fi

# Deploy the stack
log_info "Deploying FrontendStack..."
log_info "Frontend Bucket Name: ${CDK_FRONTEND_BUCKET_NAME:-<auto-generated>}"

# Optional: Use --require-approval never for CI/CD
REQUIRE_APPROVAL="${CDK_REQUIRE_APPROVAL:-never}"

# Deploy with explicit context to ensure correct region/account
OUTPUTS_FILE="${CDK_DIR}/frontend-outputs.json"

if [ -n "${CDK_APP}" ]; then
    # Deploy using pre-synthesized template
    cdk deploy FrontendStack \
        --app "${CDK_APP}" \
        --require-approval ${REQUIRE_APPROVAL} \
        --outputs-file "${OUTPUTS_FILE}" \
        --verbose
else
    # Deploy with context parameters (will synthesize first)
    cdk deploy FrontendStack \
        --require-approval ${REQUIRE_APPROVAL} \
        --outputs-file "${OUTPUTS_FILE}" \
        --context projectPrefix="${CDK_PROJECT_PREFIX}" \
        --context awsAccount="${CDK_AWS_ACCOUNT}" \
        --context awsRegion="${CDK_AWS_REGION}" \
        --context appVersion="${CDK_APP_VERSION}" \
        --context production="${CDK_PRODUCTION}" \
        --context vpcCidr="${CDK_VPC_CIDR}" \
        --context infrastructureHostedZoneDomain="${CDK_HOSTED_ZONE_DOMAIN}" \
        --context domainName="${CDK_DOMAIN_NAME}" \
        --context frontend.certificateArn="${CDK_FRONTEND_CERTIFICATE_ARN}" \
        --context frontend.bucketName="${CDK_FRONTEND_BUCKET_NAME}" \
        --context frontend.enabled="${CDK_FRONTEND_ENABLED}" \
        --context frontend.cloudFrontPriceClass="${CDK_FRONTEND_CLOUDFRONT_PRICE_CLASS}" \
        --verbose
fi

# Check deployment exit code
DEPLOY_EXIT_CODE=$?

if [ ${DEPLOY_EXIT_CODE} -eq 0 ]; then
    log_info "FrontendStack deployed successfully!"
    
    # Retrieve key outputs from CloudFormation
    log_info "Key resources deployed:"
    aws cloudformation describe-stacks \
        --stack-name ${CDK_PROJECT_PREFIX}-FrontendStack \
        --region ${CDK_AWS_REGION} \
        --query 'Stacks[0].Outputs[?OutputKey==`WebsiteUrl` || OutputKey==`DistributionId` || OutputKey==`FrontendBucketName`].[OutputKey,OutputValue]' \
        --output table || log_warn "Could not retrieve stack outputs"
    
else
    log_error "FrontendStack deployment failed with exit code: ${DEPLOY_EXIT_CODE}"
    exit ${DEPLOY_EXIT_CODE}
fi
