/**
 * Environment Configuration - Production
 * 
 * RUNTIME CONFIGURATION TAKES PRECEDENCE:
 * In production deployments, configuration is loaded from /config.json at application startup.
 * The config.json file is generated by the CDK frontend stack and contains:
 * - appApiUrl: Application Load Balancer URL (from SSM parameter)
 * - environment: Environment identifier ('production' or 'development')
 * 
 * These values below serve as FALLBACK ONLY if config.json cannot be loaded.
 * In normal production operation, these values are NOT used.
 * 
 * Fallback Behavior:
 * - If /config.json fetch fails (network error, missing file, etc.)
 * - ConfigService automatically falls back to these placeholder values
 * - Application continues to function with fallback configuration
 * - Warning is logged to console indicating fallback is active
 * 
 * Configuration Flow:
 * 1. Application starts
 * 2. APP_INITIALIZER triggers ConfigService.loadConfig()
 * 3. HTTP GET /config.json is attempted
 * 4. On success: Runtime config is used
 * 5. On failure: These fallback values are used
 * 
 * DO NOT modify these values for deployment configuration.
 * Configuration is managed by CDK infrastructure stack.
 */
export const environment = {
    production: true,
    // Runtime values loaded from /config.json
    // These are placeholders for fallback only
    appApiUrl: '',
    version: ''
};
